# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 239435147cba0f8af5b83d8397aca3d090528c10bfb4a1376b9cd51bfdfdfb6a34574ce72b5c074efb621e4ef5add43843fa0d2ec27f58533fac317a3fafe8f1

test:
  secret_key_base: 186beb426b802cd9defb9c6055ac68b92f8414144d9e32fc3fc9dd937377bad9b37977cde83a14877ab8bc3317dc2910bd8eb345fdc04688b711c14ab63d11e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
